[project]
name = "morse-cat-stats"
version = "0.1.0"
description = "Stats from Morse Cat practice data"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.0",
    "pandas>=2.2.3",
    "pyqt5>=5.15.11",
]
